<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet"></head><body style="background: background: rgb(248, 248, 248); font-family: "Quicksand", sans-serif; font-size: 15px; margin: 0; @import url("https://fonts.googleapis.com/css2?family=Quicksand&display=swap");"><div class="container" style="background-color:white; max-width: 1000px; margin: 0px auto; position: relative"><div class="row" style=" padding: 10px; background: #bde884; margin-bottom: 10px;"><div class="col-4 mx-auto" style="margin: 0px auto; width: 33.33% !important;"><img src="https://rocktera-assets.com/assets/open/images/logo-home5.png" alt="rockteraassets_logo" class="img-fluid{LOGO}" style="width: 100%; vertical-align: middle;"></div></div><p>Hello {firstname},</p>

<p style="text-align: center;"><strong>NOTIFICATION OF WEBSITE UPDATE</strong></p>

<p style="margin-left: 40px;">This is to inform the admin of<a href="https://www.rocktera-assets.com"> Rockters-assets.com</a> that an update has been added to your website.<img alt="laugh" src="https://rocktera-assets.com/assets/dashboard/vendors/js/editors/ckeditor/plugins/smiley/images/teeth_smile.png" style="height:23px; width:23px" title="laugh" /></p>

<p style="margin-left: 40px;">This a test mail on the update. You can now add <strong><span style="background-color:#00FF00">email templates</span></strong> that can be forwarded <strong>personally</strong> to one user or in a <em><strong>bulk</strong></em> mail <u>ie newsletter.</u><img alt="mail" src="https://rocktera-assets.com/assets/dashboard/vendors/js/editors/ckeditor/plugins/smiley/images/envelope.png" style="height:23px; width:23px" title="mail" /></p>

<p style="margin-left: 40px; text-align: right;"><strong>Thank You for Your,</strong></p>

<p style="margin-left: 40px; text-align: right;"><strong>Patience.<img alt="yes" src="https://rocktera-assets.com/assets/dashboard/vendors/js/editors/ckeditor/plugins/smiley/images/thumbs_up.png" style="height:23px; width:23px" title="yes" /></strong></p>
<a href="https://rocktera-assets.com/signin" class="btn" style="margin: 15px auto; display: inline-block; text-align: center; padding: 16px 30px; border-radius: 4px; color: white; background-color: #73ae20; text-decoration: none;">Dashboard</a><p>If you have any questions, please reply to this email. I’m always happy to help!</p><footer style="background-color: white; color: #c7c7c7; text-align: center; font-size: 10px;"><div style="background-color: #73ae20; color: white; padding: 20px 0px;"><p>Great to have you on board</p></div><center style="padding: 10px;"><p>Dalton House, 60 Windsor Ave, London SW19 2RR, United Kingdom</p><span style="margin: 3px 7px;">Mail: support@rocktera-assets.com</span></center></footer></div></body></html>